import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-slate-700 ${inter.className}`}>
        <div className="gradient" />
        <nav className="fixed z-20 top-0 w-full flex justify-between p-6 items-center">
          <p className="text-2xl font-semibold">
            prompt<span className="text-indigo-500">land</span>
          </p>
          <button className="normalBtn">Sign In</button>
        </nav>
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
