import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GoogleProvider from "@/components/GoogleProvider";
import Nav from "@/components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-slate-700 ${inter.className}`}>
        <div className="gradient" />
        <GoogleProvider>
          <Nav />
          <main className="relative z-10">{children}</main>
        </GoogleProvider>
      </body>
    </html>
  );
}
